name: Publish APT repo from Release assets

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (vd: v1.2.3). Bỏ trống = latest"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  apt-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Tải .deb về tạm để sinh Packages, nhưng KHÔNG publish .deb lên gh-pages
      - name: Download .deb from Release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: ${{ github.repository }}
          latest: ${{ inputs.tag == '' }}
          tag: ${{ inputs.tag }}
          fileName: "*.deb"
          out-file-path: work/pool    # work dir only

      - name: Build Packages/Packages.gz with pool/vX.Y.Z paths
        run: |
          sudo apt-get update && sudo apt-get install -y dpkg-dev
          set -e
          TAG="${{ inputs.tag }}"
          if [ -z "$TAG" ]; then
            # Lấy tag từ tên file .deb (giả sử file có _<version>_amd64.deb trùng tag v<version>)
            TAG="$(ls work/pool/*.deb | sed -E 's/.*_([0-9][^_]*)_amd64\.deb/\1/' | head -n1)"
            TAG="v${TAG}"
          fi
          mkdir -p aptrepo/pool/"$TAG"
          # Đổi tên file cho sạch (tùy bạn, có thể giữ nguyên)
          for f in work/pool/*.deb; do
            bn="$(basename "$f")"
            cp "$f" "aptrepo/pool/$TAG/$bn"
          done

          pushd aptrepo
          # Quan trọng: chạy scan trên root để Filename là pool/<tag>/<file>.deb (đường dẫn tương đối)
          dpkg-scanpackages . /dev/null > Packages
          gzip -9c Packages > Packages.gz
          popd

          echo "== Index built with TAG=$TAG =="
          ls -lah aptrepo
          awk 'NR<=50{print}' aptrepo/Packages || true

      - name: Publish ONLY index to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./aptrepo