name: Publish APT repo from Release assets

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (vd: v1.2.3). Bỏ trống = latest"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  apt-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Tải .deb từ Release về thư mục tạm, không up .deb lên gh-pages
      - name: Download .deb from Release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: ${{ github.repository }}
          latest: ${{ inputs.tag == '' }}
          tag: ${{ inputs.tag }}
          fileName: "*.deb"
          out-file-path: work/pool

      - name: Build Packages/Packages.gz with pool/vX.Y.Z paths
        run: |
          sudo apt-get update && sudo apt-get install -y dpkg-dev jq curl
          set -euo pipefail

          # 1) Lấy TAG
          TAG="${{ inputs.tag }}"
          if [ -z "$TAG" ]; then
            TAG="$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)"
          fi
          echo "Using TAG=$TAG"

          # 2) Tạo thư mục pool/<TAG>
          mkdir -p aptrepo/pool/"$TAG"

          # 3) Copy file .deb vào pool/<TAG> (chỉ copy file, không copy thư mục)
          shopt -s nullglob
          for f in work/pool/*.deb; do
            bn="$(basename "$f")"
            cp "$f" "aptrepo/pool/$TAG/$bn"
            echo "Copied: $bn"
          done

          # 4) Kiểm tra có file .deb hay không
          if ! ls aptrepo/pool/"$TAG"/*.deb >/dev/null 2>&1; then
            echo "ERROR: No .deb files found."
            exit 1
          fi

          # 5) Sinh Packages & Packages.gz
          pushd aptrepo >/dev/null
          dpkg-scanpackages . /dev/null > Packages
          gzip -9c Packages > Packages.gz
          popd >/dev/null

          # 6) Xoá pool nếu không muốn upload file nặng lên gh-pages
          rm -rf aptrepo/pool
          echo "Index built for TAG=$TAG. pool/ removed to avoid large uploads."

      - name: Publish ONLY index to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./aptrepo