name: Release FlyEnv Windows

on:
  workflow_dispatch:
  push:
  release:
    types: [published]

jobs:
  build-packages:
    name: Build  ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - arch: x64
            os: windows-latest
            target: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: 'latest'
            architecture: 'x64'
            cache: 'pip'

      - name: Install Electron build dependencies
        run: |
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
          choco install make
          choco install 7zip

      - name: Setup Latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Cache node_modules and node-gyp
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            **/node_modules
            .yarn/cache
            ~/.cache/node-gyp
          key: ${{ runner.os }}-electron-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn and build tools
        run: |
          npm install -g yarn node-gyp
          python -m pip install --upgrade pip

      - name: Install dependencies with Yarn
        run: |
          yarn install

      - name: Init notarize.ts File
        run: |
          echo "export default async function notarizing() { return; }" > build/notarize.ts

      - name: Build Electron packages with electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build

